### PR TITLE
Fix/publisher failure

### LINKED ISSUE #5: Build still failing
https://jitpack.io/com/github/sampingantech/Image-Support/1.1.1/build.log

1. Needs to use maven publisher from android instead and readjust config for maven as well https://developer.android.com/studio/build/maven-publish-plugin

### PR DESCRIPTION
**Pull request by anangkur**
close #5 
close #6

### CODE REVIEW

**Comment by mochadwi** [comment]
this also means Closes #6

**Comment by mochadwi** [comment]
LGTM, but requires changes on README.md

you can use search/find all & replaces appraoch instead to make sure all occurrences is replaced, e.g:

find: `1.1.` (yes, try to search `1.1.` or `1.0.`) this ways our search result will show which files is not updated

replace with: `1.1.2`

@anangkur

**Review by mochadwi — CHANGES_REQUESTED** [review]
LGTM, but requires changes on README.md

you can use search/find all & replaces appraoch instead to make sure all occurrences is replaced, e.g:

find: `1.1.` (yes, try to search `1.1.` or `1.0.`) this ways our search result will show which remaining files is not updated

replace with: `1.1.2`

@anangkur

**Comment by anangkur** [comment]
> LGTM, but requires changes on README.md
> 
> you can use search/find all & replaces appraoch instead to make sure all occurrences is replaced, e.g:
> 
> find: `1.1.` (yes, try to search `1.1.` or `1.0.`) this ways our search result will show which remaining files is not updated
> 
> replace with: `1.1.2`
> 
> @anangkur

alright mas, will double check for the version. thank you :pray:

**Comment by mochadwi** [comment]
> > LGTM, but requires changes on README.md
> > you can use search/find all & replaces appraoch instead to make sure all occurrences is replaced, e.g:
> > find: `1.1.` (yes, try to search `1.1.` or `1.0.`) this ways our search result will show which remaining files is not updated
> > replace with: `1.1.2`
> > @anangkur
> 
> alright mas, will double check for the version. thank you 🙏

*there's a missing statement:

> > LGTM, but requires changes on README.md & remaining files

**Comment by anangkur** [comment]
mas @mochadwi do we need to change this? `support/build.gradle line 40-49` 
image

**Comment by mochadwi** [comment]
> mas @mochadwi do we need to change this? `support/build.gradle line 40-49` 
> image

Ahh, good catch. For now add `todo: will update this lib to sampingantech jcenter`

Because it's related to jcenter publisher, we're currently using jitpack.io

Thanks @anangkur

**Comment by anangkur** [comment]
> > > LGTM, but requires changes on README.md
> > > you can use search/find all & replaces appraoch instead to make sure all occurrences is replaced, e.g:
> > > find: `1.1.` (yes, try to search `1.1.` or `1.0.`) this ways our search result will show which remaining files is not updated
> > > replace with: `1.1.2`
> > > @anangkur
> > 
> > 
> > alright mas, will double check for the version. thank you pray
> 
> *there's a missing statement:
> 
> > > LGTM, but requires changes on README.md & remaining files

I have searched `1.1.` and `1.0.` in whole project and change it to `1.1.2` . please review this once more mas @mochadwi and @adesamp . thank you 🙏🏽

**Review by mochadwi — APPROVED** [review]
LGTM

**Pull request merged**
